# Generated by Django 3.0.4 on 2020-03-28 09:47

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('objects', accounts.managers.PersonManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='operation',
            name='value',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='person',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
        migrations.AddField(
            model_name='operation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Money payment/repayment amount'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Your email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Your name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this person should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether person can log into the admin site', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Your surname'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='description',
            field=models.TextField(help_text='Maximum 300 letters available', max_length=300, verbose_name='Description for current wallet'),
        ),
    ]
