# Generated by Django 3.0.4 on 2020-03-28 10:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200328_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='Your birth date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='living_place',
            field=models.CharField(blank=True, max_length=70, verbose_name='Your living place'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=70, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Your phone number'),
        ),
    ]
