# Generated by Django 3.0.4 on 2020-03-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200328_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(auto_now=True, verbose_name='Your birth date'),
        ),
    ]
