# Generated by Django 3.0.4 on 2020-03-30 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200329_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
