# Generated by Django 3.0.4 on 2020-04-03 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_person_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Your name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Your surname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=70, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Middle name'),
        ),
    ]
