# Generated by Django 3.0.4 on 2020-04-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200404_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Your current balance'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('₽', 'RUB'), ('₴', 'UAH'), ('$', 'USD'), ('€', 'EUR'), ('£', 'GBP')], default=None, max_length=8, verbose_name='Wallet currency'),
        ),
    ]
