# Generated by Django 3.0.4 on 2020-04-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200405_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='option',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('REPLINISHMENT', 'Replinishment')], max_length=13, verbose_name='Operation type'),
        ),
    ]
