# Generated by Django 3.0.4 on 2020-04-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200410_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='wallet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Wallet'),
        ),
    ]
