# Generated by Django 3.0.4 on 2020-04-11 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200411_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Wallet'),
            preserve_default=False,
        ),
    ]
