# Generated by Django 3.0.4 on 2020-04-26 09:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200411_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email already exists.'}, max_length=254, unique=True, verbose_name='Your email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'This phone number already exists.'}, max_length=128, region=None, unique=True, verbose_name='Your phone number'),
        ),
    ]
